### ISSUE TITLE
Question about linear.Seq.String()

### ISSUE THREAD

**Issue by blankclemens** [biogo/biogo#45]
First of all: I'm new to go, so there is a high chance that I carry a lot of misunderstanding with me - I'm glad for any help (e.g. if my approach is totally wrong), feel free to correct me anytime.

I want to read FASTA sequences and perform some basic tasks on them, e.g. searching for a pattern/splitting it up by a pattern etc. Classical string stuff. Therefore I thought about reading them in and converting them to a String. However, this method is missing for me, for example this code (`test.fasta` just consist of one FASTA Sequence):

```go
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/biogo/biogo/alphabet"
	"github.com/biogo/biogo/io/seqio/fasta"
	"github.com/biogo/biogo/seq/linear"
)

func main() {

	inName := "test.fasta"

	var in *fasta.Reader

	if f, err := os.Open(inName); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v.", err)
		os.Exit(1)
	} else {
		in = fasta.NewReader(f, linear.NewSeq("", nil, alphabet.DNA))
		defer f.Close()
	}

	s, err := in.Read()
	if err != nil {
		if err != io.EOF {
			fmt.Printf("Error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	r := linear.NewSeq("example RNA", []alphabet.Letter("ACGCTGACTTGGTGCACGT"), alphabet.DNA)

	fmt.Printf("%T \n", r)
	fmt.Printf("%T \n", s)
}
```

Prints out:

```
*linear.Seq
*linear.Seq
```

As type for `r` and `s`. However, only `r` has the method `String()`. So I wonder:

1. Why is this the case?
2. How can I convert my sequences read from a file to strings, in order to perform string operations? 
3. And is this even a proper approach? ;-)

Thank you very much for any help and for providing this library!

Clemens

**Comment by kortschak** [comment]
Hi.

1. The concrete types *do* have the `String() string` method, but the method is not necessary for the function of the sequence type, so it is not included. The apparent confusion you have about the output of `%T` for the two values is that both have the same concrete type, but one (`r`) is a `*linear.Seq` and the other is a `seq.Sequence`. Reading the [laws of reflection](https://blog.golang.org/laws-of-reflection) will help you understand this.
2. Really you should not convert the sequence to a string. It causes an allocation that is unnecessary. If you type assert your value to `*linear.Seq` (which you know it to be since you asked the reader to create those), you have direct access to the sequence data.
3. How I would get toward where you want to be (untested).
```
package main

import (
	"fmt"
	"os"
	"regexp"

	"github.com/biogo/biogo/alphabet"
	"github.com/biogo/biogo/io/seqio"
	"github.com/biogo/biogo/io/seqio/fasta"
	"github.com/biogo/biogo/seq/linear"
)

func init() {
	re := regexp.MustCompile("ga..ct")
}

func main() {
	inName := "test.fasta"

	if f, err := os.Open(inName); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v.", err)
		os.Exit(1)
	}
	r := fasta.NewReader(f, linear.NewSeq("", nil, alphabet.DNA))
	defer f.Close()

	sc := seqio.NewScanner(r)
	for sc.Next() {
		s := sc.Seq().(*linear.Seq)
		l := alphabet.LetterToBytes(s.Seq)
		fmt.Printlf("%s\n", re.FindAll(l))
	}
}
```

Having said that. I don't think regexps are a good match for this kind of work.

**Comment by blankclemens** [comment]
Thank you so much!

1. That was an interesting read! Although I probably didn't fully understand everything, it was a big step forward ;) 
2. Ok, so through my template `linear.NewSeq` I told my reader to create `*linear.Seq` types. And I can access them, if I type assert them via `Seq().(*linear.Seq)`.
While I can't imagine as of now how I will ever see how this could be intuitive or easy to find out, it does work and I'm hopeful that with growing knowledge I might see it. 😄 
Using `LetterToBytes` doesn't have the overhead of the string conversion because Letters are already bytes (+ using the unsafe package for performance)?
3. Therefore it most likely makes sense to just use the `bytes` package to do all the string stuff on bytes with high performance. Nice.

Thank you!
