### ISSUE TITLE
Testsuite is failing

### ISSUE THREAD

**Issue by nileshpatra** [biogo/biogo#85]
Hi @kortschak 

Thanks a lot for your work on biogo. I maintain this as a package in Debian, and during a recent re-build, tests have started to fail for biogo, in particular these:

```
=== RUN   Test

----------------------------------------------------------------------
FAIL: errors_test.go:44: S.TestCaller

errors_test.go:49:
    c.Check(ln, check.Equals, 45)
... obtained int = 46
... expected int = 45

=== RUN   Test

----------------------------------------------------------------------
FAIL: fai_test.go:27: S.TestReadFrom

fai_test.go:178:
    c.Assert(err, check.DeepEquals, t.err)
... obtained *csv.ParseError = &csv.ParseError{StartLine:8, Line:8, Column:1, Err:(*errors.errorString)(0xc0000563f0)} ("record on line 8: wrong number of fields")
... expected *csv.ParseError = &csv.ParseError{StartLine:8, Line:8, Column:0, Err:(*errors.errorString)(0xc0000563f0)} ("record on line 8: wrong number of fields")
... Difference:
...     Column: 1 != 0


OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.00s)
FAIL
FAIL	github.com/biogo/biogo/io/seqio/fai	0.023s
```

Full log can be found [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=997551) please consider fixing. There is some delta in col values that seems to trigger this, but I cannot do much beyond this point. Please consider fixing this, and thanks again!

**Comment by kortschak** [comment]
The issue is a result of changes in the way csv.Parser returns errors (https://go-review.googlesource.com/c/go/+/314774/). The fix is trivially to change the expected column, but I have limited time at the moment and this is not a package that I am actively using, so it may take some time to get to this.

In the interim, I don't see any problem with you altering that expect value in your build if you know that you are only supporting Go 1.17. The issue for the general fix is the infrastructure needed to make the expectation conditional on Go version.

**Comment by kortschak** [comment]
I have removed the tests from that package since it's been deprecated for a while and the actual logic is already tested elsewhere. I have also fixed or deprecated other failing issues.

**Comment by nileshpatra** [comment]
Thanks a lot.

Would you please consider doing a point release with this fix? That'd help
me pull the update and fix the corresponding debian package more cleanly.

Let me know.

**Comment by kortschak** [comment]
Would a v1.0.4 work for you? There are no functional changes.

**Comment by nileshpatra** [comment]
Sure, that'd be great!
